# pull official base image
FROM node:16.1.0-alpine AS build

RUN mkdir build
# set working directory
WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm ci --silent

# add app
#COPY public/ public
#COPY src/ src

COPY public/ public
COPY src/ src
RUN npm run build

FROM httpd:alpine
WORKDIR /var/www/html
COPY --from=build /build/build/ .
